/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new Employee
         * @description Registers a new employee aggregate in the global system.
         */
        post: operations["register_employee_api_v1_auth_employees_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/employees/{employee_id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign franchise role to Employee
         * @description Assigns a role to an employee within a specific tenant franchise.
         */
        post: operations["assign_role_api_v1_auth_employees__employee_id__roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Employee Franchise Login
         * @description Authenticates credentials, checks franchise access, and establishes a stateful Session.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Employee Session Logout
         * @description Invalidates and deletes the active stateful session.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get authenticated Employee profile
         * @description Returns the profile of the currently logged-in employee.
         */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all Menus */
        get: operations["list_menus_api_v1_menu_get"];
        put?: never;
        /** Create a new Menu */
        post: operations["create_menu_api_v1_menu_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu/{menu_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a Menu by ID */
        get: operations["get_menu_api_v1_menu__menu_id__get"];
        put?: never;
        post?: never;
        /** Delete a Menu */
        delete: operations["delete_menu_api_v1_menu__menu_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu/{menu_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add an item to a Menu */
        post: operations["add_menu_item_api_v1_menu__menu_id__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu/{menu_id}/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove an item from a Menu */
        delete: operations["remove_menu_item_api_v1_menu__menu_id__items__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu/{menu_id}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Activate or deactivate a Menu */
        patch: operations["toggle_menu_api_v1_menu__menu_id__toggle_patch"];
        trace?: never;
    };
    "/api/v1/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new Order Form */
        post: operations["create_order_api_v1_order_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/order/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get active Order Form by ID */
        get: operations["get_order_api_v1_order__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/order/{order_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add an item to an active Order Form */
        post: operations["add_order_item_api_v1_order__order_id__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/order/{order_id}/request-payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request payment (lock) for an active Order Form */
        post: operations["request_payment_api_v1_order__order_id__request_payment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/order/{order_id}/process-payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process payment for an active Order Form */
        post: operations["process_payment_api_v1_order__order_id__process_payment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/order/{order_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel an active Order Form */
        post: operations["cancel_order_api_v1_order__order_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/order/{order_id}/deliver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deliver/complete an active Order Form, close it, and sync to MongoDB */
        post: operations["deliver_order_api_v1_order__order_id__deliver_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/order/history/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get completed Order History read models from MongoDB */
        get: operations["get_order_history_api_v1_order_history_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kitchen/items/{id}/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Prepare Item
         * @description Transitions a kitchen order item to the PREPARING state, scoped to tenant.
         */
        patch: operations["prepare_item_api_v1_kitchen_items__id__prepare_patch"];
        trace?: never;
    };
    "/api/v1/kitchen/items/{id}/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Mark Item Ready
         * @description Transitions a kitchen order item to the READY state, scoped to tenant.
         */
        patch: operations["mark_item_ready_api_v1_kitchen_items__id__ready_patch"];
        trace?: never;
    };
    "/api/v1/kitchen/items/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Cancel Item
         * @description Transitions a kitchen order item to the CANCELLED state, scoped to tenant.
         */
        patch: operations["cancel_item_api_v1_kitchen_items__id__cancel_patch"];
        trace?: never;
    };
    "/api/v1/kitchen/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Active Items
         * @description Returns a list of all active (non-terminal) kitchen items for the specified station and tenant.
         */
        get: operations["get_active_items_api_v1_kitchen_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request payment transaction processing
         * @description Processes a new payment transaction (via Stripe or locally for cash) and persists state.
         */
        post: operations["request_payment_api_v1_payments_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/refund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refund a completed payment transaction
         * @description Processes a refund transaction through external Stripe gateway or locally for cash.
         */
        post: operations["refund_payment_api_v1_payments_refund_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/order/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get payment record by Order ID
         * @description Fetches the payment read model for a specific order under the tenant.
         */
        get: operations["get_payment_by_order_api_v1_payments_order__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all stock items */
        get: operations["list_stock_items_api_v1_stock_items_get"];
        put?: never;
        /** Create a new stock item */
        post: operations["create_stock_item_api_v1_stock_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a stock item by ID */
        get: operations["get_stock_item_api_v1_stock_items__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock/items/{item_id}/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add stock to an item */
        post: operations["add_stock_api_v1_stock_items__item_id__add_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock/items/{item_id}/deduct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deduct stock from an item */
        post: operations["deduct_stock_api_v1_stock_items__item_id__deduct_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock/items/{item_id}/min-level": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set minimum stock level */
        put: operations["set_min_stock_level_api_v1_stock_items__item_id__min_level_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock/items/{item_id}/adjust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adjust stock to an absolute quantity */
        post: operations["adjust_stock_api_v1_stock_items__item_id__adjust_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock/items/{item_id}/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get movement history for a stock item */
        get: operations["get_stock_movements_api_v1_stock_items__item_id__movements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_v1_analytics_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sales Report */
        get: operations["get_sales_report_api_v1_analytics_sales_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Order Insights */
        get: operations["get_order_insights_api_v1_analytics_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/kitchen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Kitchen Performance */
        get: operations["get_kitchen_performance_api_v1_analytics_kitchen_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalyticsPeriod
         * @enum {string}
         */
        AnalyticsPeriod: "day" | "week" | "month" | "custom";
        /**
         * AssignRoleSchema
         * @description Schema for assigning a role to an Employee.
         */
        AssignRoleSchema: {
            /**
             * Tenant Id
             * @description Tenant franchise ID
             */
            tenant_id: number;
            /** @description Role type (e.g. MANAGER, WAITER, COOK, CASHIER) */
            role_type: components["schemas"]["RoleType"];
        };
        /**
         * EmployeeRegisterSchema
         * @description Schema for registering a new Employee.
         */
        EmployeeRegisterSchema: {
            /**
             * Id
             * @description Unique employee identifier
             */
            id: number;
            /**
             * Name
             * @description Full name of the employee
             */
            name: string;
            /**
             * Email
             * Format: email
             * @description Validated corporate email address
             */
            email: string;
            /**
             * Password
             * @description Plaintext password, min 6 characters
             */
            password: string;
        };
        /**
         * EmployeeResponseSchema
         * @description Schema for returning Employee information.
         */
        EmployeeResponseSchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Email */
            email: string;
        };
        /** FulfillmentResponseSchema */
        FulfillmentResponseSchema: {
            /** Type */
            type: string | null;
            /** Fee */
            fee: string;
            /** Table Number */
            table_number?: number | null;
            /** Customer Name */
            customer_name?: string | null;
            /** Delivery Street */
            delivery_street?: string | null;
            /** Delivery Number */
            delivery_number?: string | null;
            /** Delivery Neighborhood */
            delivery_neighborhood?: string | null;
            /** Delivery City */
            delivery_city?: string | null;
            /** Delivery State */
            delivery_state?: string | null;
            /** Delivery Postal Code */
            delivery_postal_code?: string | null;
            /** Delivery Estimated Time */
            delivery_estimated_time?: number | null;
            /** Delivery Tracking Code */
            delivery_tracking_code?: number | null;
            /** Delivery State Name */
            delivery_state_name?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginSchema
         * @description Schema for logging in.
         */
        LoginSchema: {
            /**
             * Email
             * Format: email
             * @description Employee corporate email
             */
            email: string;
            /**
             * Password
             * @description Plaintext password
             */
            password: string;
            /**
             * Tenant Id
             * @description Target tenant franchise ID to login into
             */
            tenant_id: number;
        };
        /** MenuCreateSchema */
        MenuCreateSchema: {
            /**
             * Id
             * @description Unique menu identifier
             */
            id: number;
            /**
             * Name
             * @description Menu display name
             */
            name: string;
            /**
             * Description
             * @description Optional description
             * @default
             */
            description: string;
        };
        /** MenuItemAddSchema */
        MenuItemAddSchema: {
            /**
             * Id
             * @description Unique item identifier
             */
            id: number;
            /**
             * Name
             * @description Item name
             */
            name: string;
            /**
             * Description
             * @description Item description
             * @default
             */
            description: string;
            /**
             * Category
             * @description Category name (e.g. 'Bebidas', 'Pratos')
             */
            category: string;
            /**
             * Image Url
             * @description Optional image URL
             */
            image_url?: string | null;
            /**
             * Is Available
             * @description Availability flag
             * @default true
             */
            is_available: boolean;
        };
        /** MenuItemSchema */
        MenuItemSchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Category */
            category: string;
            /** Image Url */
            image_url?: string | null;
            /**
             * Is Available
             * @default true
             */
            is_available: boolean;
        };
        /** MenuResponseSchema */
        MenuResponseSchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["MenuItemSchema"][];
        };
        /** MenuToggleSchema */
        MenuToggleSchema: {
            /**
             * Activate
             * @description True to activate, False to deactivate
             */
            activate: boolean;
        };
        /** MinStockLevelSchema */
        MinStockLevelSchema: {
            /**
             * Min Stock Level
             * @description New minimum stock level
             */
            min_stock_level: number;
        };
        /** OrderCreateSchema */
        OrderCreateSchema: {
            /**
             * Id
             * @description Unique order identifier
             */
            id: number;
            /**
             * Fulfillment Type
             * @description Type of fulfillment: TABLE, TAKEAWAY, or DELIVERY
             */
            fulfillment_type: string;
            /**
             * Table Number
             * @description Table number if TABLE
             */
            table_number?: number | null;
            /**
             * Customer Name
             * @description Customer name if TAKEAWAY
             */
            customer_name?: string | null;
            /**
             * Delivery Street
             * @description Street name if DELIVERY
             */
            delivery_street?: string | null;
            /**
             * Delivery Number
             * @description House/Apartment number if DELIVERY
             */
            delivery_number?: string | null;
            /**
             * Delivery Neighborhood
             * @description Neighborhood if DELIVERY
             */
            delivery_neighborhood?: string | null;
            /**
             * Delivery City
             * @description City if DELIVERY
             */
            delivery_city?: string | null;
            /**
             * Delivery State
             * @description State if DELIVERY
             */
            delivery_state?: string | null;
            /**
             * Delivery Postal Code
             * @description Postal code if DELIVERY
             */
            delivery_postal_code?: string | null;
            /**
             * Delivery Estimated Time
             * @description Estimated delivery time in minutes
             * @default 40
             */
            delivery_estimated_time: number;
            /**
             * Delivery Tracking Code
             * @description Delivery tracking code
             * @default 0
             */
            delivery_tracking_code: number;
        };
        /** OrderItemAddSchema */
        OrderItemAddSchema: {
            /**
             * Id
             * @description Unique item identifier
             */
            id: number;
            /**
             * Menu Item Id
             * @description ID of the menuItem in the menu
             */
            menu_item_id: number;
            /**
             * Name Cpy
             * @description Snapshot name of the menuItem
             */
            name_cpy: string;
            /**
             * Price Cpy
             * @description Snapshot price of the menuItem
             */
            price_cpy: number | string;
            /**
             * Station Type Cpy
             * @description Snapshot prep station type (e.g. Grill)
             */
            station_type_cpy: string;
            /**
             * Quantity
             * @description Quantity ordered
             */
            quantity: number;
            /**
             * Notes
             * @description Optional customization notes
             * @default
             */
            notes: string;
        };
        /** OrderItemResponseSchema */
        OrderItemResponseSchema: {
            /** Id */
            id: number;
            /** Menu Item Id */
            menu_item_id: number;
            /** Name Cpy */
            name_cpy: string;
            /** Price Cpy */
            price_cpy: string;
            /** Station Type Cpy */
            station_type_cpy: string;
            /** Quantity */
            quantity: number;
            /** Notes */
            notes: string;
            /** Subtotal */
            subtotal: string;
        };
        /** OrderResponseSchema */
        OrderResponseSchema: {
            /** Id */
            id: number;
            /** Tenant Id */
            tenant_id: string;
            /** State */
            state: string;
            /** Payment Requested */
            payment_requested: boolean;
            /** Total */
            total: string;
            fulfillment: components["schemas"]["FulfillmentResponseSchema"];
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["OrderItemResponseSchema"][];
        };
        /**
         * PaymentRefundSchema
         * @description Pydantic schema representing a request to refund a completed payment.
         */
        PaymentRefundSchema: {
            /**
             * Order Id
             * @description Unique order identifier
             */
            order_id: number;
        };
        /**
         * PaymentRequestSchema
         * @description Pydantic schema representing a request to process a new payment transaction.
         */
        PaymentRequestSchema: {
            /**
             * Order Id
             * @description Unique order identifier
             */
            order_id: number;
            /**
             * Amount
             * @description Amount to be processed
             */
            amount: number | string;
            /**
             * Method
             * @description Payment method to use: CASH, CREDIT_CARD, DEBIT_CARD, or PIX
             */
            method: string;
        };
        /**
         * PaymentResponseSchema
         * @description Pydantic schema representing a completed payment response.
         */
        PaymentResponseSchema: {
            /** Id */
            id: number;
            /** Order Id */
            order_id: number;
            /** Tenant Id */
            tenant_id: string;
            /** Amount */
            amount: string;
            /** Method */
            method: string;
            /** Status */
            status: string;
            /** Gateway Ref */
            gateway_ref?: string | null;
            /** Failure Reason */
            failure_reason?: string | null;
        };
        /**
         * RoleType
         * @enum {string}
         */
        RoleType: "MANAGER" | "WAITER" | "COOK" | "CASHIER";
        /**
         * SessionResponseSchema
         * @description Schema returning session details after successful login.
         */
        SessionResponseSchema: {
            /**
             * Session Id
             * @description Bearer session token identifier
             */
            session_id: string;
            /**
             * Expires At
             * Format: date-time
             * @description Session expiration timestamp
             */
            expires_at: string;
        };
        /** StockAddSchema */
        StockAddSchema: {
            /**
             * Quantity
             * @description Positive quantity to add
             */
            quantity: number;
            /**
             * Reason
             * @description Reason for stock addition
             * @default
             */
            reason: string;
            /**
             * Reference Type
             * @description Order type, etc.
             */
            reference_type?: string | null;
            /**
             * Reference Id
             * @description Related entity ID
             */
            reference_id?: number | null;
        };
        /** StockAdjustSchema */
        StockAdjustSchema: {
            /**
             * New Quantity
             * @description Absolute new quantity (physical count)
             */
            new_quantity: number;
            /**
             * Reason
             * @default Inventory adjustment
             */
            reason: string;
        };
        /** StockDeductSchema */
        StockDeductSchema: {
            /**
             * Quantity
             * @description Positive quantity to deduct
             */
            quantity: number;
            /**
             * Reason
             * @description Reason for stock deduction
             * @default
             */
            reason: string;
            /**
             * Reference Type
             * @description Order type, etc.
             */
            reference_type?: string | null;
            /**
             * Reference Id
             * @description Related entity ID
             */
            reference_id?: number | null;
        };
        /** StockItemCreateSchema */
        StockItemCreateSchema: {
            /**
             * Id
             * @description Unique stock item identifier
             */
            id: number;
            /**
             * Name
             * @description Item name
             */
            name: string;
            /**
             * Category
             * @description Category (RAW_MATERIAL, BEVERAGE, etc.)
             */
            category: string;
            /**
             * Current Quantity
             * @description Initial quantity
             * @default 0
             */
            current_quantity: number;
            /**
             * Unit
             * @description Measurement unit (g, kg, ml, l, un)
             * @default un
             */
            unit: string;
            /**
             * Min Stock Level
             * @description Minimum stock alert level
             * @default 0
             */
            min_stock_level: number;
        };
        /** StockItemResponseSchema */
        StockItemResponseSchema: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Current Quantity Amount */
            current_quantity_amount: number;
            /** Current Quantity Unit */
            current_quantity_unit: string;
            /** Min Stock Level */
            min_stock_level: number;
            /** Is Active */
            is_active: boolean;
            /** Is Low Stock */
            is_low_stock: boolean;
        };
        /** StockMovementResponseSchema */
        StockMovementResponseSchema: {
            /** Id */
            id: number;
            /** Stock Item Id */
            stock_item_id: number;
            /** Movement Type */
            movement_type: string;
            /** Quantity Changed */
            quantity_changed: number;
            /** Reason */
            reason: string;
            /** Reference Type */
            reference_type?: string | null;
            /** Reference Id */
            reference_id?: number | null;
            /** Created At */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_employee_api_v1_auth_employees_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeRegisterSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_role_api_v1_auth_employees__employee_id__roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRoleSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeResponseSchema"];
                };
            };
        };
    };
    list_menus_api_v1_menu_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuResponseSchema"][];
                };
            };
        };
    };
    create_menu_api_v1_menu_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuCreateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_menu_api_v1_menu__menu_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                menu_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_menu_api_v1_menu__menu_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                menu_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_menu_item_api_v1_menu__menu_id__items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                menu_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuItemAddSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuItemSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_menu_item_api_v1_menu__menu_id__items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                menu_id: number;
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_menu_api_v1_menu__menu_id__toggle_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                menu_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuToggleSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_order_api_v1_order_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_api_v1_order__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_order_item_api_v1_order__order_id__items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderItemAddSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderItemResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_payment_api_v1_order__order_id__request_payment_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_payment_api_v1_order__order_id__process_payment_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_order_api_v1_order__order_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deliver_order_api_v1_order__order_id__deliver_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_history_api_v1_order_history_all_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    prepare_item_api_v1_kitchen_items__id__prepare_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_item_ready_api_v1_kitchen_items__id__ready_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_item_api_v1_kitchen_items__id__cancel_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_active_items_api_v1_kitchen_items_get: {
        parameters: {
            query: {
                station_type: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_payment_api_v1_payments_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentRequestSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refund_payment_api_v1_payments_refund_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentRefundSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_payment_by_order_api_v1_payments_order__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stock_items_api_v1_stock_items_get: {
        parameters: {
            query?: {
                /** @description Filter low stock items only */
                low_stock_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockItemResponseSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_stock_item_api_v1_stock_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockItemCreateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockItemResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stock_item_api_v1_stock_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockItemResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_stock_api_v1_stock_items__item_id__add_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockAddSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockItemResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deduct_stock_api_v1_stock_items__item_id__deduct_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockDeductSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockItemResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_min_stock_level_api_v1_stock_items__item_id__min_level_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MinStockLevelSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockItemResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adjust_stock_api_v1_stock_items__item_id__adjust_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockAdjustSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockItemResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stock_movements_api_v1_stock_items__item_id__movements_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockMovementResponseSchema"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_api_v1_analytics_dashboard_get: {
        parameters: {
            query?: {
                period?: components["schemas"]["AnalyticsPeriod"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sales_report_api_v1_analytics_sales_get: {
        parameters: {
            query?: {
                period?: components["schemas"]["AnalyticsPeriod"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order_insights_api_v1_analytics_orders_get: {
        parameters: {
            query?: {
                period?: components["schemas"]["AnalyticsPeriod"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_kitchen_performance_api_v1_analytics_kitchen_get: {
        parameters: {
            query?: {
                period?: components["schemas"]["AnalyticsPeriod"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
