"""add_reason_to_stock_transactions

Revision ID: c7c2dbc5d5de
Revises: 4c8a9e3b1f2d
Create Date: 2026-06-08 21:16:49.790348+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c7c2dbc5d5de'
down_revision: str | None = '4c8a9e3b1f2d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_form_items', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.add_column('stock_transactions', sa.Column('reason', sa.String(length=500), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_transactions', 'reason')
    op.alter_column('order_form_items', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'WAITING'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
