"""refactor_stock_pattern_and_recipes

Revision ID: 9947b94ba12d
Revises: 419be8d9893e
Create Date: 2026-06-05 19:23:23.754324+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9947b94ba12d"
down_revision: str | None = "419be8d9893e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("menu_item_id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recipes_menu_item_id"), "recipes", ["menu_item_id"], unique=False)
    op.create_index(op.f("ix_recipes_tenant_id"), "recipes", ["tenant_id"], unique=False)
    op.create_table(
        "composite_stock_item_relations",
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["child_id"], ["stock_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["stock_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("parent_id", "child_id"),
    )
    op.create_table(
        "recipe_ingredients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("stock_item_id", sa.Integer(), nullable=False),
        sa.Column("quantity_value", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("quantity_unit", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["stock_item_id"], ["stock_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recipe_ingredients_recipe_id"), "recipe_ingredients", ["recipe_id"], unique=False
    )
    op.create_index(
        op.f("ix_recipe_ingredients_stock_item_id"),
        "recipe_ingredients",
        ["stock_item_id"],
        unique=False,
    )
    op.create_table(
        "stock_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stock_item_id", sa.Integer(), nullable=False),
        sa.Column("transaction_type", sa.String(length=20), nullable=False),
        sa.Column("quantity_value", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("quantity_unit", sa.String(length=20), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["stock_item_id"], ["stock_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stock_transactions_stock_item_id"),
        "stock_transactions",
        ["stock_item_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_stock_movements_stock_item_id"), table_name="stock_movements")
    op.drop_table("stock_movements")
    op.add_column("stock_items", sa.Column("type", sa.String(length=50), nullable=False))
    op.add_column("stock_items", sa.Column("unit", sa.String(length=20), nullable=False))
    op.drop_column("stock_items", "current_quantity_unit")
    op.drop_column("stock_items", "current_quantity_amount")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stock_items",
        sa.Column(
            "current_quantity_amount",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "stock_items",
        sa.Column(
            "current_quantity_unit", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("stock_items", "unit")
    op.drop_column("stock_items", "type")
    op.create_table(
        "stock_movements",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("stock_item_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("movement_type", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "quantity_changed",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("reason", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column("reference_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("reference_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["stock_item_id"],
            ["stock_items.id"],
            name=op.f("stock_movements_stock_item_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("stock_movements_pkey")),
    )
    op.create_index(
        op.f("ix_stock_movements_stock_item_id"), "stock_movements", ["stock_item_id"], unique=False
    )
    op.drop_index(op.f("ix_stock_transactions_stock_item_id"), table_name="stock_transactions")
    op.drop_table("stock_transactions")
    op.drop_index(op.f("ix_recipe_ingredients_stock_item_id"), table_name="recipe_ingredients")
    op.drop_index(op.f("ix_recipe_ingredients_recipe_id"), table_name="recipe_ingredients")
    op.drop_table("recipe_ingredients")
    op.drop_table("composite_stock_item_relations")
    op.drop_index(op.f("ix_recipes_tenant_id"), table_name="recipes")
    op.drop_index(op.f("ix_recipes_menu_item_id"), table_name="recipes")
    op.drop_table("recipes")
    # ### end Alembic commands ###
