"""add canceled_quantity to order_form_items

Revision ID: ce8a9ac16c6c
Revises: 2bca53e024e4
Create Date: 2026-06-14 16:52:34.234093+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce8a9ac16c6c"
down_revision: str | None = "2bca53e024e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_form_items",
        sa.Column("canceled_quantity", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_form_items", "canceled_quantity")
    # ### end Alembic commands ###
