"""Add failure_reason to payments

Revision ID: 92630e2a4cc4
Revises: f7195407d48d
Create Date: 2026-06-02 12:57:09.973910+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '92630e2a4cc4'
down_revision: str | None = 'f7195407d48d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('failure_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'failure_reason')
    # ### end Alembic commands ###
