"""add previous_state to kitchen items

Revision ID: 39fdcde076d1
Revises: af558bf78ae7
Create Date: 2026-06-15 02:00:02.061039+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39fdcde076d1"
down_revision: str | None = "af558bf78ae7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "kitchen_order_items", sa.Column("previous_state", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("kitchen_order_items", "previous_state")
    # ### end Alembic commands ###
