"""create_order_schema

Revision ID: 427ac74e0c5e
Revises: 39bcfa5696a0
Create Date: 2026-06-02 11:50:08.026735+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "427ac74e0c5e"
down_revision: str | None = "39bcfa5696a0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_forms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column("state", sa.String(length=50), nullable=False),
        sa.Column("payment_requested", sa.Boolean(), nullable=False),
        sa.Column("fulfillment_type", sa.String(length=50), nullable=True),
        sa.Column("table_number", sa.Integer(), nullable=True),
        sa.Column("customer_name", sa.String(length=255), nullable=True),
        sa.Column("delivery_street", sa.String(length=255), nullable=True),
        sa.Column("delivery_number", sa.String(length=50), nullable=True),
        sa.Column("delivery_neighborhood", sa.String(length=255), nullable=True),
        sa.Column("delivery_city", sa.String(length=255), nullable=True),
        sa.Column("delivery_state", sa.String(length=50), nullable=True),
        sa.Column("delivery_postal_code", sa.String(length=20), nullable=True),
        sa.Column("delivery_estimated_time", sa.Integer(), nullable=True),
        sa.Column("delivery_tracking_code", sa.Integer(), nullable=True),
        sa.Column("delivery_state_name", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_order_forms_tenant_id"), "order_forms", ["tenant_id"], unique=False)
    op.create_table(
        "order_form_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("menu_item_id", sa.Integer(), nullable=False),
        sa.Column("name_cpy", sa.String(length=255), nullable=False),
        sa.Column("price_cpy", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("station_type_cpy", sa.String(length=100), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["order_id"], ["order_forms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_form_items")
    op.drop_index(op.f("ix_order_forms_tenant_id"), table_name="order_forms")
    op.drop_table("order_forms")
    # ### end Alembic commands ###
