"""add_role_permissions_and_audit_logs

Revision ID: afa78038d50d
Revises: 71b1e6481fdb
Create Date: 2026-06-12 22:32:55.646004+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "afa78038d50d"
down_revision: str | None = "71b1e6481fdb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("actor_name", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=True),
        sa.Column("entity_id", sa.String(length=50), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["employees.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "role_permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("role_type", sa.String(length=50), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "kitchen_order_items",
        "preparation_profile",
        existing_type=sa.VARCHAR(length=50),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "menu_items",
        "preparation_profile",
        existing_type=sa.VARCHAR(length=50),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index(
        op.f("uq_active_display_code"),
        table_name="order_forms",
        postgresql_where="((state)::text <> ALL ((ARRAY['PAID'::character varying, 'CLOSED'::character varying])::text[]))",
    )
    op.alter_column(
        "stock_transactions",
        "reason",
        existing_type=sa.VARCHAR(length=500),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stock_transactions",
        "reason",
        existing_type=sa.VARCHAR(length=500),
        server_default=sa.text("''::character varying"),
        existing_nullable=False,
    )
    op.create_index(
        op.f("uq_active_display_code"),
        "order_forms",
        ["tenant_id", "display_code"],
        unique=True,
        postgresql_where="((state)::text <> ALL ((ARRAY['PAID'::character varying, 'CLOSED'::character varying])::text[]))",
    )
    op.alter_column(
        "menu_items",
        "preparation_profile",
        existing_type=sa.VARCHAR(length=50),
        server_default=sa.text("'STANDARD'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "kitchen_order_items",
        "preparation_profile",
        existing_type=sa.VARCHAR(length=50),
        server_default=sa.text("'STANDARD'::character varying"),
        existing_nullable=False,
    )
    op.drop_table("role_permissions")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
