"""add tenant_id to menu and price_list tables

Revision ID: 096bc067d550
Revises: 5e8a2f9b3c1d
Create Date: 2026-06-02 14:54:40.696065+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '096bc067d550'
down_revision: str | None = '5e8a2f9b3c1d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('tenant_id', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_menus_tenant_id'), 'menus', ['tenant_id'], unique=False)
    op.add_column('price_lists', sa.Column('tenant_id', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_price_lists_tenant_id'), 'price_lists', ['tenant_id'], unique=False)
    op.alter_column('stock_items', 'current_quantity_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stock_items', 'min_stock_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('stock_items', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_stock_items_name_tenant'), table_name='stock_items')
    op.alter_column('stock_movements', 'reason',
               existing_type=sa.VARCHAR(length=500),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_movements', 'reason',
               existing_type=sa.VARCHAR(length=500),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.create_index(op.f('ix_stock_items_name_tenant'), 'stock_items', ['name', 'tenant_id'], unique=True)
    op.alter_column('stock_items', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('stock_items', 'min_stock_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.alter_column('stock_items', 'current_quantity_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0'::double precision"),
               existing_nullable=False)
    op.drop_index(op.f('ix_price_lists_tenant_id'), table_name='price_lists')
    op.drop_column('price_lists', 'tenant_id')
    op.drop_index(op.f('ix_menus_tenant_id'), table_name='menus')
    op.drop_column('menus', 'tenant_id')
    # ### end Alembic commands ###
