"""remove_unique_correlation_id

Revision ID: 2b02812ac9cf
Revises: 8a7ce3d89d66
Create Date: 2026-06-13 14:24:07.584134+00:00

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b02812ac9cf"
down_revision: str | None = "8a7ce3d89d66"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_kitchen_order_items_correlation_id"), table_name="kitchen_order_items")
    op.create_index(
        op.f("ix_kitchen_order_items_correlation_id"),
        "kitchen_order_items",
        ["correlation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_kitchen_order_items_correlation_id"), table_name="kitchen_order_items")
    op.create_index(
        op.f("ix_kitchen_order_items_correlation_id"),
        "kitchen_order_items",
        ["correlation_id"],
        unique=True,
    )
    # ### end Alembic commands ###
