"""create_kitchen_schema

Revision ID: dff1f0947a78
Revises: 427ac74e0c5e
Create Date: 2026-06-02 12:30:15.287419+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dff1f0947a78"
down_revision: str | None = "427ac74e0c5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kitchen_order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("correlation_id", sa.Integer(), nullable=False),
        sa.Column("name_cpy", sa.String(length=255), nullable=False),
        sa.Column("station_type_cpy", sa.String(length=100), nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column("state", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_kitchen_order_items_correlation_id"),
        "kitchen_order_items",
        ["correlation_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_kitchen_order_items_tenant_id"), "kitchen_order_items", ["tenant_id"], unique=False
    )
    op.create_table(
        "kitchen_stations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("station_type", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_kitchen_stations_tenant_id"), "kitchen_stations", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_kitchen_stations_tenant_id"), table_name="kitchen_stations")
    op.drop_table("kitchen_stations")
    op.drop_index(op.f("ix_kitchen_order_items_tenant_id"), table_name="kitchen_order_items")
    op.drop_index(op.f("ix_kitchen_order_items_correlation_id"), table_name="kitchen_order_items")
    op.drop_table("kitchen_order_items")
    # ### end Alembic commands ###
