"""refactor_menu_item_aggregate

Revision ID: 419be8d9893e
Revises: 096bc067d550
Create Date: 2026-06-03 23:51:30.576613+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "419be8d9893e"
down_revision: str | None = "096bc067d550"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category_items",
        sa.Column("menu_id", sa.Integer(), nullable=False),
        sa.Column("category_name", sa.String(length=100), nullable=False),
        sa.Column("menu_item_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["menu_id"], ["menus.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["menu_item_id"], ["menu_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("menu_id", "category_name", "menu_item_id"),
    )
    op.add_column("menu_items", sa.Column("tenant_id", sa.String(length=255), nullable=False))
    op.add_column(
        "menu_items", sa.Column("base_price", sa.Numeric(precision=10, scale=2), nullable=False)
    )
    op.add_column("menu_items", sa.Column("station_type", sa.String(length=100), nullable=False))
    op.add_column("menu_items", sa.Column("category_name", sa.String(length=100), nullable=False))
    op.create_index(op.f("ix_menu_items_tenant_id"), "menu_items", ["tenant_id"], unique=False)
    op.drop_constraint(op.f("menu_items_menu_id_fkey"), "menu_items", type_="foreignkey")
    op.drop_column("menu_items", "menu_id")
    op.drop_column("menu_items", "category")
    op.add_column("menus", sa.Column("price_list_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "menus", "price_lists", ["price_list_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "menus", type_="foreignkey")
    op.drop_column("menus", "price_list_id")
    op.add_column(
        "menu_items",
        sa.Column("category", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.add_column(
        "menu_items", sa.Column("menu_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key(
        op.f("menu_items_menu_id_fkey"),
        "menu_items",
        "menus",
        ["menu_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_menu_items_tenant_id"), table_name="menu_items")
    op.drop_column("menu_items", "category_name")
    op.drop_column("menu_items", "station_type")
    op.drop_column("menu_items", "base_price")
    op.drop_column("menu_items", "tenant_id")
    op.drop_table("category_items")
    # ### end Alembic commands ###
