"""add delivered_quantity to order_items

Revision ID: 8a7ce3d89d66
Revises: c4d5e6f7a8b9
Create Date: 2026-06-12 23:15:17.417967+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a7ce3d89d66"
down_revision: str | None = "c4d5e6f7a8b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employee_permissions",
        "granted",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.create_foreign_key(
        None, "employee_permissions", "employees", ["employee_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "employee_permissions", "tenants", ["tenant_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column(
        "order_form_items",
        sa.Column("delivered_quantity", sa.Integer(), nullable=False, server_default=sa.text("0")),
    )
    op.alter_column(
        "user_tenant_roles",
        "removed",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_tenant_roles",
        "removed",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.drop_column("order_form_items", "delivered_quantity")
    op.drop_constraint(None, "employee_permissions", type_="foreignkey")
    op.drop_constraint(None, "employee_permissions", type_="foreignkey")
    op.alter_column(
        "employee_permissions",
        "granted",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
