sequenceDiagram
    participant Cliente as Cliente
    participant API as API
    participant Domain as Domain Order
    participant PG as PostgreSQL
    participant MONGO as MongoDB

    Cliente->>API: POST /order/1/request-payment
    API->>Domain: find_by_id(1, tid)
    Domain->>PG: SELECT WHERE id + tenant_id
    PG-->>Domain: OrderForm
    Domain->>Domain: order.request_payment()
    Domain-->>API: OK
    API-->>Cliente: 200 OK

    Cliente->>API: POST /order/1/process-payment
    API->>Domain: find_by_id(1, tid)
    Domain->>PG: SELECT WHERE id + tenant_id
    PG-->>Domain: OrderForm
    Domain->>Domain: order.process_payment()<br/>Open → Paid
    Domain-->>API: OK
    API-->>Cliente: 200 OK

    Cliente->>API: POST /order/1/deliver
    API->>Domain: find_by_id(1, tid)
    Domain->>PG: SELECT WHERE id + tenant_id
    PG-->>Domain: OrderForm
    Domain->>Domain: order.deliver()
    Domain-->>API: OK
    API->>PG: save(order)<br/>UPDATE WHERE id + tenant_id
    PG-->>API: OK

    Note over API,MONGO: BackgroundTask(2): sync MongoDB
    API->>MONGO: OrderHistoryMongo.save(order)<br/>upsert → order_history
    API->>MONGO: OrderReadModelSync.sync(order)<br/>upsert → orders_read

    API-->>Cliente: 200 + OrderResponse